"""
Flask project structure generator

Generates a complete, production-ready Flask project structure
with all necessary configuration files, directories, and boilerplate code.
"""

import os
from typing import Dict, List, Optional
from datetime import datetime


class FlaskStructureGenerator:
    """Generates complete Flask project structure"""

    def __init__(self, output_dir: str, project_config: Optional[Dict] = None):
        """
        Initialize Flask structure generator

        Args:
            output_dir: Output directory for Flask project
            project_config: Optional configuration dict with project metadata
        """
        self.output_dir = output_dir
        self.config = project_config or {}
        self.project_name = self.config.get('project_name', 'flask_app')

    def generate_complete_structure(self):
        """Generate all necessary Flask files and directories"""
        print(f"[Flask Generator] Generating Flask project structure in: {self.output_dir}")

        self.create_directory_structure()
        self.generate_app_factory()
        self.generate_config()
        self.generate_requirements()
        self.generate_env_file()
        self.generate_wsgi()
        self.generate_readme()
        self.generate_init_files()
        self.generate_gitignore()
        self.generate_dockerfile()

        print("[Flask Generator] Flask project structure generated successfully!")

    def create_directory_structure(self):
        """Create Flask project directories"""
        dirs = [
            'app',
            'app/models',
            'app/views',
            'app/templates',
            'app/templates/base',
            'app/static',
            'app/static/css',
            'app/static/js',
            'app/static/images',
            'migrations',
            'tests',
            'tests/unit',
            'tests/integration',
            'instance',
            'logs',
        ]

        for dir_path in dirs:
            full_path = os.path.join(self.output_dir, dir_path)
            os.makedirs(full_path, exist_ok=True)

        print(f"[Flask Generator] Created {len(dirs)} directories")

    def generate_app_factory(self):
        """Generate app/__init__.py with app factory pattern"""
        app_init = '''"""
Flask application factory
Auto-generated by FrameShift
"""
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from config import config

# Initialize extensions
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message = 'Please log in to access this page.'


def create_app(config_name='default'):
    """
    Application factory pattern

    Args:
        config_name: Configuration to use ('development', 'production', 'testing')

    Returns:
        Flask application instance
    """
    app = Flask(__name__, instance_relative_config=True)

    # Load configuration
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Ensure instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # Register blueprints
    from app.views import register_blueprints
    register_blueprints(app)

    # Register error handlers
    register_error_handlers(app)

    # Shell context for flask shell command
    @app.shell_context_processor
    def make_shell_context():
        return {'db': db}

    return app


def register_error_handlers(app):
    """Register error handlers"""

    @app.errorhandler(404)
    def not_found(error):
        return {"error": "Resource not found"}, 404

    @app.errorhandler(500)
    def internal_error(error):
        db.session.rollback()
        return {"error": "Internal server error"}, 500

    @app.errorhandler(403)
    def forbidden(error):
        return {"error": "Forbidden"}, 403

    @app.errorhandler(400)
    def bad_request(error):
        return {"error": "Bad request"}, 400
'''

        self._write_file('app/__init__.py', app_init)
        print("[Flask Generator] Generated app factory")

    def generate_config(self):
        """Generate config.py with environment-specific configurations"""
        config_content = '''"""
Flask configuration
Auto-generated by FrameShift
"""
import os
from datetime import timedelta

basedir = os.path.abspath(os.path.dirname(__file__))


class Config:
    """Base configuration"""

    # Security
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'dev-secret-key-change-in-production'

    # Database
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_RECORD_QUERIES = True
    SQLALCHEMY_ECHO = False

    # Session configuration
    PERMANENT_SESSION_LIFETIME = timedelta(days=7)
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'

    # Upload configuration
    MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16MB max file size
    UPLOAD_FOLDER = os.path.join(basedir, 'uploads')

    # Pagination
    ITEMS_PER_PAGE = 20

    @staticmethod
    def init_app(app):
        """Initialize application"""
        pass


class DevelopmentConfig(Config):
    """Development configuration"""
    DEBUG = True
    TESTING = False
    SQLALCHEMY_DATABASE_URI = os.environ.get('DEV_DATABASE_URL') or \\
        'sqlite:///' + os.path.join(basedir, 'instance', 'dev.db')
    SQLALCHEMY_ECHO = True
    SESSION_COOKIE_SECURE = False


class ProductionConfig(Config):
    """Production configuration"""
    DEBUG = False
    TESTING = False
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \\
        'postgresql://user:password@localhost/dbname'

    @classmethod
    def init_app(cls, app):
        """Production-specific initialization"""
        Config.init_app(app)

        # Log to syslog
        import logging
        from logging.handlers import SysLogHandler
        syslog_handler = SysLogHandler()
        syslog_handler.setLevel(logging.WARNING)
        app.logger.addHandler(syslog_handler)


class TestingConfig(Config):
    """Testing configuration"""
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    WTF_CSRF_ENABLED = False
    SESSION_COOKIE_SECURE = False


# Configuration dictionary
config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}
'''

        self._write_file('config.py', config_content)
        print("[Flask Generator] Generated configuration")

    def generate_requirements(self):
        """Generate requirements.txt with all necessary packages"""
        requirements = '''# Flask core
Flask==3.0.0
Flask-SQLAlchemy==3.1.1
Flask-Migrate==4.0.5
Flask-Login==0.6.3

# Database
psycopg2-binary==2.9.9  # PostgreSQL adapter
SQLAlchemy==2.0.23

# Security
python-dotenv==1.0.0
email-validator==2.1.0

# Development tools
pytest==7.4.3
pytest-cov==4.1.0
black==23.12.1
flake8==6.1.0

# WSGI server
gunicorn==21.2.0
'''

        self._write_file('requirements.txt', requirements)
        print("[Flask Generator] Generated requirements.txt")

    def generate_env_file(self):
        """Generate .env.example file"""
        env_content = '''# Flask Configuration
FLASK_APP=wsgi.py
FLASK_ENV=development
SECRET_KEY=your-secret-key-here

# Database
DEV_DATABASE_URL=sqlite:///instance/dev.db
DATABASE_URL=postgresql://user:password@localhost/dbname

# Email (Optional)
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=True
MAIL_USERNAME=your-email@gmail.com
MAIL_PASSWORD=your-password

# Application
DEBUG=True
'''

        self._write_file('.env.example', env_content)
        print("[Flask Generator] Generated .env.example")

    def generate_wsgi(self):
        """Generate wsgi.py entry point"""
        wsgi_content = '''"""
WSGI entry point
Auto-generated by FrameShift
"""
import os
from dotenv import load_dotenv

# Load environment variables
dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)

from app import create_app

# Create application instance
app = create_app(os.getenv('FLASK_ENV') or 'default')

if __name__ == '__main__':
    app.run()
'''

        self._write_file('wsgi.py', wsgi_content)
        print("[Flask Generator] Generated wsgi.py")

    def generate_readme(self):
        """Generate comprehensive README.md"""
        readme_content = f'''# {self.project_name}

> Flask application converted from Django by FrameShift

## 🚀 Quick Start

### Prerequisites

- Python 3.8+
- pip
- virtualenv (recommended)

### Installation

1. **Clone the repository** (or navigate to this directory)

2. **Create virtual environment**
   ```bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   ```

3. **Install dependencies**
   ```bash
   pip install -r requirements.txt
   ```

4. **Set up environment variables**
   ```bash
   cp .env.example .env
   # Edit .env with your configuration
   ```

5. **Initialize database**
   ```bash
   flask db init
   flask db migrate -m "Initial migration"
   flask db upgrade
   ```

6. **Run the application**
   ```bash
   flask run
   ```

   The application will be available at `http://localhost:5000`

## 📁 Project Structure

```
{self.project_name}/
├── app/                    # Application package
│   ├── __init__.py        # App factory
│   ├── models/            # Database models
│   ├── views/             # View functions/routes
│   ├── templates/         # Jinja2 templates
│   └── static/            # Static files (CSS, JS, images)
├── migrations/            # Database migrations
├── tests/                 # Test suite
│   ├── unit/             # Unit tests
│   └── integration/      # Integration tests
├── instance/              # Instance-specific files (not in version control)
├── logs/                  # Application logs
├── config.py              # Configuration classes
├── wsgi.py               # WSGI entry point
├── requirements.txt       # Python dependencies
└── README.md             # This file
```

## 🛠 Development

### Running Tests

```bash
pytest
```

### Database Migrations

```bash
# Create a new migration
flask db migrate -m "Description of changes"

# Apply migrations
flask db upgrade

# Rollback migration
flask db downgrade
```

### Code Formatting

```bash
# Format code with black
black .

# Check code style
flake8
```

## 🚢 Deployment

### Using Gunicorn

```bash
gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
```

### Using Docker

```bash
docker build -t {self.project_name} .
docker run -p 8000:8000 {self.project_name}
```

### Environment Variables

Make sure to set these environment variables in production:

- `SECRET_KEY` - Secret key for session encryption
- `DATABASE_URL` - PostgreSQL database URL
- `FLASK_ENV` - Set to `production`

## 📝 Notes

- This project was automatically converted from Django to Flask by FrameShift
- Review the generated code and make necessary adjustments
- Update database models and relationships as needed
- Configure authentication and authorization
- Add custom views and templates

## 🐛 Known Issues

- Some complex Django features may require manual adjustment
- Check the conversion report for warnings and suggestions

## 📚 Resources

- [Flask Documentation](https://flask.palletsprojects.com/)
- [Flask-SQLAlchemy](https://flask-sqlalchemy.palletsprojects.com/)
- [Flask-Migrate](https://flask-migrate.readthedocs.io/)

---

**Converted by FrameShift** - Django to Flask Migration Tool
'''

        self._write_file('README.md', readme_content)
        print("[Flask Generator] Generated README.md")

    def generate_init_files(self):
        """Generate __init__.py files for Python packages"""
        init_files = [
            'app/models/__init__.py',
            'app/views/__init__.py',
            'tests/__init__.py',
            'tests/unit/__init__.py',
            'tests/integration/__init__.py',
        ]

        # Generate models __init__.py
        models_init = '''"""
Database models
"""
from app import db

# Import all models here
# from .user import User
# from .post import Post
'''
        self._write_file('app/models/__init__.py', models_init)

        # Generate views __init__.py with blueprint registration
        views_init = '''"""
Application views and blueprints
"""
from flask import Blueprint


def register_blueprints(app):
    """
    Register all blueprints

    Args:
        app: Flask application instance
    """
    # Import and register blueprints here
    # from .main import main_bp
    # app.register_blueprint(main_bp)

    # Example: Health check endpoint
    @app.route('/health')
    def health_check():
        return {"status": "healthy"}, 200

    pass
'''
        self._write_file('app/views/__init__.py', views_init)

        # Generate test __init__.py files
        self._write_file('tests/__init__.py', '"""Test suite"""')
        self._write_file('tests/unit/__init__.py', '"""Unit tests"""')
        self._write_file('tests/integration/__init__.py', '"""Integration tests"""')

        print("[Flask Generator] Generated __init__.py files")

    def generate_gitignore(self):
        """Generate .gitignore file"""
        gitignore_content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Flask
instance/
.env
.flaskenv
*.db
*.sqlite

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Logs
logs/
*.log

# Testing
.coverage
htmlcov/
.pytest_cache/

# Migrations (optional - remove if you want to track migrations)
# migrations/
'''

        self._write_file('.gitignore', gitignore_content)
        print("[Flask Generator] Generated .gitignore")

    def generate_dockerfile(self):
        """Generate Dockerfile for containerization"""
        dockerfile_content = f'''FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    gcc \\
    postgresql-client \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create necessary directories
RUN mkdir -p instance logs

# Expose port
EXPOSE 8000

# Set environment variables
ENV FLASK_APP=wsgi.py
ENV PYTHONUNBUFFERED=1

# Run gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "wsgi:app"]
'''

        self._write_file('Dockerfile', dockerfile_content)
        print("[Flask Generator] Generated Dockerfile")

    def _write_file(self, relative_path: str, content: str):
        """
        Write content to a file

        Args:
            relative_path: Path relative to output_dir
            content: File content
        """
        full_path = os.path.join(self.output_dir, relative_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)

        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(content.strip() + '\n')


def generate_flask_skeleton(output_dir: str, project_config: Optional[Dict] = None):
    """
    Convenience function to generate Flask skeleton

    Args:
        output_dir: Output directory for Flask project
        project_config: Optional configuration dict

    Returns:
        FlaskStructureGenerator instance
    """
    generator = FlaskStructureGenerator(output_dir, project_config)
    generator.generate_complete_structure()
    return generator
