"""
Smart Flask Project Generator
Analyzes converted code and generates a proper, runnable Flask application
"""

import os
import ast
from pathlib import Path
from typing import Dict, List, Set
from ..utils.logger import logger


class SmartFlaskGenerator:
    """
    Generates a complete, runnable Flask project by analyzing the converted code
    """

    def __init__(self, project_path: str, project_name: str):
        self.project_path = Path(project_path)
        self.project_name = project_name
        self.apps = []
        self.models = []
        self.has_auth = False
        self.has_forms = False
        self.dependencies = set()

    def analyze_project(self):
        """Analyze converted code to understand project structure"""
        logger.info(f"Analyzing project: {self.project_name}")

        # Find all app directories (account, job, jobapp, etc.)
        for item in self.project_path.iterdir():
            if item.is_dir() and not item.name.startswith(('.', '__')):
                self.apps.append(item.name)

                # Check if app has models
                models_file = item / 'models.py'
                if models_file.exists():
                    self._analyze_models(models_file, item.name)

                # Check if app has routes
                routes_file = item / 'routes.py'
                if routes_file.exists():
                    self._analyze_routes(routes_file)

        logger.info(f"Found {len(self.apps)} apps: {', '.join(self.apps)}")
        logger.info(f"Found {len(self.models)} models")

    def _analyze_models(self, models_file: Path, app_name: str):
        """Analyze models file to find model classes"""
        try:
            content = models_file.read_text(encoding='utf-8')

            # Simple regex to find class definitions
            import re
            classes = re.findall(r'class\s+(\w+)\s*\(.*\):', content)

            for class_name in classes:
                self.models.append({
                    'name': class_name,
                    'app': app_name
                })

            # Check for authentication models
            if 'User' in classes or 'CustomUser' in classes:
                self.has_auth = True

        except Exception as e:
            logger.warn(f"Error analyzing {models_file}: {e}")

    def _analyze_routes(self, routes_file: Path):
        """Analyze routes to understand features"""
        try:
            content = routes_file.read_text(encoding='utf-8')

            # Check for forms
            if 'WTForms' in content or 'FlaskForm' in content:
                self.has_forms = True

        except Exception as e:
            logger.warn(f"Error analyzing {routes_file}: {e}")

    def generate_app_py(self) -> str:
        """Generate main app.py file"""

        blueprints_import = []
        blueprints_register = []

        for app in self.apps:
            bp_name = f"{app}_bp"
            blueprints_import.append(f"from {app}.routes import {bp_name}")
            blueprints_register.append(f"    app.register_blueprint({bp_name}, url_prefix='/{app}')")

        blueprints_import_str = '\n'.join(blueprints_import) if blueprints_import else "    # No blueprints found"
        blueprints_register_str = '\n'.join(blueprints_register) if blueprints_register else "    # No blueprints to register"

        auth_imports = ""
        auth_init = ""
        if self.has_auth:
            auth_imports = "\nfrom flask_login import LoginManager"
            auth_init = """
    # Initialize Flask-Login
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'account.login'

    @login_manager.user_loader
    def load_user(user_id):
        from account.models import User
        return User.query.get(int(user_id))
"""

        return f'''"""
{self.project_name} - Flask Application
Auto-generated by FrameShift
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate{auth_imports}

# Initialize extensions
db = SQLAlchemy()
migrate = Migrate()

def create_app(config_name='development'):
    """Application factory pattern"""
    app = Flask(__name__)

    # Load configuration
    from config import config
    app.config.from_object(config[config_name])

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
{auth_init}

    # Register blueprints
{blueprints_register_str}

    # Import models to ensure they're registered with SQLAlchemy
{self._generate_model_imports()}

    # Create database tables
    with app.app_context():
        db.create_all()

    @app.route('/')
    def index():
        return "Welcome to {self.project_name}!"

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0', port=5000)
'''

    def _generate_model_imports(self) -> str:
        """Generate imports for all models"""
        imports = []
        apps_done = set()

        for model in self.models:
            if model['app'] not in apps_done:
                imports.append(f"    from {model['app']}.models import *")
                apps_done.add(model['app'])

        return '\n'.join(imports) if imports else "    # No models found"

    def generate_config_py(self) -> str:
        """Generate config.py"""
        return f'''"""
Configuration for {self.project_name}
Auto-generated by FrameShift
"""

import os
from pathlib import Path

# Build paths
basedir = Path(__file__).resolve().parent

class Config:
    """Base configuration"""
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'dev-secret-key-change-in-production'
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # Session configuration
    SESSION_TYPE = 'filesystem'
    PERMANENT_SESSION_LIFETIME = 1800  # 30 minutes

class DevelopmentConfig(Config):
    """Development configuration"""
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = os.environ.get('DEV_DATABASE_URL') or \\
        'sqlite:///' + str(basedir / 'dev.db')
    SQLALCHEMY_ECHO = True  # Log SQL queries

class ProductionConfig(Config):
    """Production configuration"""
    DEBUG = False
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \\
        'sqlite:///' + str(basedir / 'prod.db')

class TestingConfig(Config):
    """Testing configuration"""
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    WTF_CSRF_ENABLED = False

# Configuration dictionary
config = {{
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}}
'''

    def generate_requirements_txt(self) -> str:
        """Generate requirements.txt based on features used"""
        requirements = [
            "Flask==3.0.0",
            "Flask-SQLAlchemy==3.1.1",
            "Flask-Migrate==4.0.5",
        ]

        if self.has_auth:
            requirements.append("Flask-Login==0.6.3")

        if self.has_forms:
            requirements.append("Flask-WTF==1.2.1")
            requirements.append("WTForms==3.1.1")

        requirements.extend([
            "python-dotenv==1.0.0",
            "Werkzeug==3.0.1",
        ])

        return '\n'.join(requirements) + '\n'

    def generate_env_example(self) -> str:
        """Generate .env.example"""
        return f'''# {self.project_name} Environment Variables
# Copy this file to .env and update with your values

# Flask Configuration
FLASK_APP=app.py
FLASK_ENV=development
SECRET_KEY=your-secret-key-here

# Database
DEV_DATABASE_URL=sqlite:///dev.db
DATABASE_URL=sqlite:///prod.db

# Debug Mode
FLASK_DEBUG=1
'''

    def generate_gitignore(self) -> str:
        """Generate .gitignore"""
        return '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Flask
instance/
.webassets-cache
*.db
*.sqlite
*.sqlite3

# Environment
.env
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/
'''

    def generate_readme_md(self) -> str:
        """Generate README.md"""
        models_list = '\n'.join([f"- {m['name']} ({m['app']})" for m in self.models[:10]])
        if len(self.models) > 10:
            models_list += f"\n- ... and {len(self.models) - 10} more"

        return f'''# {self.project_name}

Converted from Django to Flask using **FrameShift**.

## Project Structure

```
{self.project_name}/
├── app.py              # Main application entry point
├── config.py           # Configuration settings
├── requirements.txt    # Python dependencies
├── .env.example        # Environment variables template
{self._generate_structure_tree()}
└── templates/          # Jinja2 templates
```

## Models

{models_list if self.models else "No models found"}

## Quick Start

### 1. Install Dependencies

```bash
pip install -r requirements.txt
```

### 2. Set Up Environment

```bash
cp .env.example .env
# Edit .env with your configuration
```

### 3. Initialize Database

```bash
flask db init
flask db migrate -m "Initial migration"
flask db upgrade
```

### 4. Run the Application

```bash
python app.py
```

The application will be available at `http://localhost:5000`

## Development

### Running in Development Mode

```bash
export FLASK_ENV=development
export FLASK_DEBUG=1
python app.py
```

### Database Migrations

```bash
# Create a new migration
flask db migrate -m "Description of changes"

# Apply migrations
flask db upgrade

# Rollback migration
flask db downgrade
```

## Production Deployment

### Using Gunicorn

```bash
pip install gunicorn
gunicorn -w 4 -b 0.0.0.0:5000 "app:create_app()"
```

### Environment Variables

Make sure to set these in production:

- `SECRET_KEY`: Strong secret key for sessions
- `DATABASE_URL`: Production database URL
- `FLASK_ENV`: Set to `production`

## Notes

- This project was automatically converted from Django to Flask
- Review all routes and models for correctness
- Test thoroughly before deploying to production
- Some features may need manual adjustments

## Apps

{', '.join(self.apps) if self.apps else "No apps found"}

## Support

For issues with the conversion, please check the conversion report.

---

**Generated by**: FrameShift
**Date**: Auto-generated
'''

    def _generate_structure_tree(self) -> str:
        """Generate ASCII tree of app structure"""
        tree_lines = []
        for app in self.apps:
            tree_lines.append(f"├── {app}/")
            tree_lines.append(f"│   ├── models.py")
            tree_lines.append(f"│   ├── routes.py")
            tree_lines.append(f"│   └── views.py")
        return '\n'.join(tree_lines) if tree_lines else ""

    def generate_all(self):
        """Generate all Flask project files"""
        logger.info(f"Generating runnable Flask project: {self.project_name}")

        # Analyze the project first
        self.analyze_project()

        # Generate files
        files = {
            'app.py': self.generate_app_py(),
            'config.py': self.generate_config_py(),
            'requirements.txt': self.generate_requirements_txt(),
            '.env.example': self.generate_env_example(),
            '.gitignore': self.generate_gitignore(),
            'README.md': self.generate_readme_md(),
        }

        # Write files
        for filename, content in files.items():
            file_path = self.project_path / filename
            try:
                file_path.write_text(content, encoding='utf-8')
                logger.info(f"Generated: {filename}")
            except Exception as e:
                logger.error(f"Failed to generate {filename}: {e}")

        logger.info(f"Flask project generation complete!")
        return {
            'success': True,
            'files_generated': list(files.keys()),
            'apps': self.apps,
            'models': len(self.models)
        }
